services:
  api:
    command: 
      sh -c "pytest"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - APP_NAME=FastAPI Clean Architecture
      - APP_VERSION=1.0.0
      - DEBUG=True
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/db_challenge
      - DATABASE_TEST_URL=postgresql://postgres:postgres@db_test:5432/db_challenge_test
      - SECRET_KEY=625e2e91ef6bbfed55d5dfee0f0cb548
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - API_POKEMON=https://pokeapi.co/api/v2
    depends_on:
      db_test:
        condition: service_healthy
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
    working_dir: /app

  db_test:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=db_challenge_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_test: