version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build_and_test:
    executor:
      name: python/default
      tag: '3.13'
    environment:
      APP_NAME=FastAPI Clean Architecture
      APP_VERSION=1.0.0
      DEBUG=True
      DATABASE_URL=postgresql://postgres:postgres@db_test:5432/db_challenge_test
      SECRET_KEY=625e2e91ef6bbfed55d5dfee0f0cb548
      ALGORITHM=HS256
      ACCESS_TOKEN_EXPIRE_MINUTES=30
      API_POKEMON=https://pokeapi.co/api/v2
    steps:
      - checkout

      # Restaurar cache del venv
      - restore_cache:
          keys:
            - venv-v1-{{ checksum "requirements.txt" }}
            - venv-v1-

      - run:
          name: Setup Virtual Env
          command: |
            python3 -m venv .venv
            echo "source .venv/bin/activate" >> $BASH_ENV

      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt

      # Guardar cache del venv
      - save_cache:
          paths:
            - .venv
          key: venv-v1-{{ checksum "requirements.txt" }}
      
      - run:
          name: Run Tests
          command: pytest -v
      
      # Opcional: guardar resultados de tests
      - store_test_results:
          path: test-results
      
      - store_artifacts:
          path: htmlcov

workflows:
  build_test_deploy:
    jobs:
      - build_and_test



        