version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build_and_test:
    executor:
      name: python/default
      tag: '3.13'
    environment:
      DATABASE_URL: "sqlite:///./test.db"
      SECRET_KEY: 625e2e91ef6bbfed55d5dfee04832920548
      API_POKEMON: https://pokeapi.co/api/v2
    steps:
      - checkout

      # Restaurar cache del venv
      - restore_cache:
          keys:
            - venv-v1-{{ checksum "requirements.txt" }}
            - venv-v1-

      - run:
          name: Setup Virtual Env
          command: |
            python3 -m venv .venv
            echo "source .venv/bin/activate" >> $BASH_ENV

      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt

      # Guardar cache del venv
      - save_cache:
          paths:
            - .venv
          key: venv-v1-{{ checksum "requirements.txt" }}
      
      - run:
          name: Run App
          command: uvicorn app.main:app --host 0.0.0.0 --port 8000
      
      # Opcional: guardar resultados de tests
      - store_test_results:
          path: test-results
      
      - store_artifacts:
          path: htmlcov

workflows:
  build_test_deploy:
    jobs:
      - build_and_test



        